name: Daily WOM Update

on:
  schedule:
    # 10 AM UTC = 12 PM CEST (Central European Summer Time)
    - cron: '0 10 * * *'
  workflow_dispatch:  # Allows manual trigger via GitHub UI

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run WOM clan update script
        run: python wom_clan_update.py
        env:
          WOM_VERIFICATION_CODE: ${{ secrets.WOM_VERIFICATION_CODE }}
