name: Daily WOM Update + Achievements

on:
  schedule:
    - cron: '0 10 * * *'  # 12:00 PM CEST
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Update WOM group
        run: python wom_clan_update.py
        env:
          WOM_VERIFICATION_CODE: ${{ secrets.WOM_VERIFICATION_CODE }}

      - name: Check new achievements and post to Discord
  run: python wom_check_achievements.py
  env:
    DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
