name: Daily WOM Update + Achievements

on:
  schedule:
    - cron: '0 10 * * *'  # 12:00 PM CEST
  workflow_dispatch:

jobs:
  update-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Cache achievement progress
        uses: actions/cache@v4
        with:
          path: last_achievement.json
          key: achievement-progress-${{ runner.os }}
          restore-keys: |
            achievement-progress-

      - name: Update Wise Old Man Clan
        run: python wom_clan_update.py
        env:
          WOM_VERIFICATION_CODE: ${{ secrets.WOM_VERIFICATION_CODE }}

      - name: Check and Post Achievements
        run: python wom_check_achievements.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
