name: Daily WOM Update + Achievements

on:
  schedule:
    - cron: '0 10 * * *'  # 12:00 PM CEST
  workflow_dispatch:

jobs:
  update-and-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Update Wise Old Man Clan
        run: python wom_clan_update.py
        env:
          WOM_VERIFICATION_CODE: ${{ secrets.WOM_VERIFICATION_CODE }}

      - name: Check and Post Achievements
        run: python wom_check_achievements.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Commit and push updated achievement log
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add last_achievement.json
          git commit -m "Update last_achievement.json" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_PAT }}@github.com/${{ github.repository }} HEAD:main
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
